version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:80"
    command: python manage.py runserver
    environment:
      - DB_HOST=pg_db_container
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    hostname: pg_db_container
